export const SKILLS = {
  Business: [
    "Business strategy",
    "Fund raising",
    "GTM strategy",
    "Engineering management",
    "Lean startup",
    "Agile",
  ],
  "Cloud & DevOps": [
    "Google Cloud",
    "AWS",
    "Azure",
    "Digital Ocean",
    "Docker",
    "Kubernetes",
    "Google Container Engine",
    "Scaleway",
    "New Relic",
    "K8",
    "Grafana",
  ],
  "Data & Persistence": [
    "MongoDB",
    "Postgres",
    "MySQL",
    "MSSQL",
    "Cassandra",
    "Redis",
    "RabbitMQ",
    "AWS SQS",
    "Apache Kafka",
    "Elastic Search",
    "GraphQL",
  ],
  "Server Frameworks": [
    "Node.js",
    "GO (beginner)",
    "Django",
    "Nginx",
    "Nest.js",
  ],
  "API/Libraries": [
    "Nltk",
    "Scikit-learn",
    "Twitter",
    "Facebook",
    "Instagram",
    "Youtube",
    "Google Maps",
    "Google Language",
    "Stripe",
    "Twilio",
    "Git",
  ],
  Languages: ["Javascript", "Typescript", "Python", "C#", "GO (beginner)"],
  "Front End Technologies": [
    "React",
    "React Native",
    "Flutter",
    "Bootstrap",
    "Semantic UI",
    "Ant Design",
    "Apollo GraphQL",
    "HTML",
    "CSS",
    "SCSS",
    "Wordpress",
    "Woocommerce",
  ],
}
