version: "3.8"

services:
  db:
    image: ankane/pgvector
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=koka
      - POSTGRES_USER=koka
      - POSTGRES_DB=koka

volumes:
  db:
